// <auto-generated />
using System;
using DevIO.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevIO.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DevIO.Business.Models.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeInstituicao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Bancos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d086cfcc-be97-475b-b848-fd6d83059578"),
                            CodigoBanco = "001",
                            NomeInstituicao = "Banco do Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("82806fa7-3345-45f0-ad08-a33ae7898725"),
                            CodigoBanco = "003",
                            NomeInstituicao = "Banco da Amazonia S.A."
                        },
                        new
                        {
                            Id = new Guid("87682ac7-9202-4c00-b5d0-cb1c87dd042e"),
                            CodigoBanco = "004",
                            NomeInstituicao = "Banco do Nordeste do Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("fc54a9ea-3ce7-4683-b007-b6c4e80c942a"),
                            CodigoBanco = "012",
                            NomeInstituicao = "Banco Standard de Investimentos S.A."
                        },
                        new
                        {
                            Id = new Guid("66fe57e0-bae2-4d7f-b757-1879f0f45174"),
                            CodigoBanco = "014",
                            NomeInstituicao = "Natixis Brasil S.A. Banco Múltiplo"
                        },
                        new
                        {
                            Id = new Guid("f19029ad-81a2-4948-8283-8bede97434af"),
                            CodigoBanco = "019",
                            NomeInstituicao = "Banco Azteca do Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("77b083fc-248f-411f-9b14-b313f4825931"),
                            CodigoBanco = "021",
                            NomeInstituicao = "Banestes S.A. Banco do Estado do Espírito Santo S.A."
                        },
                        new
                        {
                            Id = new Guid("a1e5e4b4-10bf-4c4b-b899-6f4fccb0147c"),
                            CodigoBanco = "024",
                            NomeInstituicao = "Banco de Pernambuco S.A. – BANDEPE"
                        },
                        new
                        {
                            Id = new Guid("c727cd3c-ee35-4447-96d1-0fae3cf08e20"),
                            CodigoBanco = "025",
                            NomeInstituicao = "Banco Alfa S.A"
                        },
                        new
                        {
                            Id = new Guid("10a18c59-8da8-4f5f-a42a-cf46c19209f9"),
                            CodigoBanco = "029",
                            NomeInstituicao = "Banco Banerj S.A"
                        },
                        new
                        {
                            Id = new Guid("174ceb9c-108f-426b-9433-ca026013ae4a"),
                            CodigoBanco = "031",
                            NomeInstituicao = "Banco Beg S.A."
                        },
                        new
                        {
                            Id = new Guid("b5617321-19dc-4e7f-b79e-99b2c7ddb562"),
                            CodigoBanco = "033",
                            NomeInstituicao = "Banco Santander (Brasil) S.A"
                        },
                        new
                        {
                            Id = new Guid("b3f9852a-35f0-41ae-8878-c99885b807b5"),
                            CodigoBanco = "036",
                            NomeInstituicao = "Banco Bradesco BBI S.A."
                        },
                        new
                        {
                            Id = new Guid("4be5aa59-78c3-475b-93e1-d4981f6bcb97"),
                            CodigoBanco = "037",
                            NomeInstituicao = "Banco do Estado do Pará S.A"
                        },
                        new
                        {
                            Id = new Guid("f6933598-54bc-461a-b812-245299b7a06c"),
                            CodigoBanco = "040",
                            NomeInstituicao = "Banco Cargil S.A"
                        },
                        new
                        {
                            Id = new Guid("e923b312-5d7d-4fcd-b44c-e75af6750106"),
                            CodigoBanco = "041",
                            NomeInstituicao = "Banco do Estado do Rio Grade do Sul S.A."
                        },
                        new
                        {
                            Id = new Guid("33f96e55-01a7-4b07-b30c-2fba43d560a5"),
                            CodigoBanco = "044",
                            NomeInstituicao = "Banco BVA S.A"
                        },
                        new
                        {
                            Id = new Guid("4dabf2c2-0b62-4fe0-a985-e988ec36f8e3"),
                            CodigoBanco = "045",
                            NomeInstituicao = "Banco Opportunity S.A."
                        },
                        new
                        {
                            Id = new Guid("9623f30a-7915-4415-b598-e9feba6bcf24"),
                            CodigoBanco = "047",
                            NomeInstituicao = "Banco do Estado de Sergipe S.A"
                        },
                        new
                        {
                            Id = new Guid("f107ea38-3c0a-470f-a103-d2212daacb68"),
                            CodigoBanco = "062",
                            NomeInstituicao = "Hipercard Banco Múltiplo S.A"
                        },
                        new
                        {
                            Id = new Guid("d5855ed0-1d1c-439d-a503-9cf816981055"),
                            CodigoBanco = "063",
                            NomeInstituicao = "Banco IBI S.A. – Banco Múltiplo"
                        },
                        new
                        {
                            Id = new Guid("beeaaf93-ad7a-4fca-bc13-ef937f5388f9"),
                            CodigoBanco = "065",
                            NomeInstituicao = "Banco Lemon S.A"
                        },
                        new
                        {
                            Id = new Guid("c0cc11ff-8fa6-443f-9395-f9f7e96ebef7"),
                            CodigoBanco = "066",
                            NomeInstituicao = "Banco Morgan Stanley S.A"
                        },
                        new
                        {
                            Id = new Guid("ab7126ec-5037-4166-905f-75494ed69726"),
                            CodigoBanco = "069",
                            NomeInstituicao = "BPN Brasil Banco Múltiplo S.A."
                        },
                        new
                        {
                            Id = new Guid("0310809a-d5e1-4330-8095-ff192a24926e"),
                            CodigoBanco = "070",
                            NomeInstituicao = "BRB – Banco de Brasilia S.A"
                        },
                        new
                        {
                            Id = new Guid("87729636-ed9e-4825-8950-99f71999e626"),
                            CodigoBanco = "072",
                            NomeInstituicao = "Banco Rural Mais S.A"
                        },
                        new
                        {
                            Id = new Guid("e6f594c2-5a25-4dee-9014-c57e2e32ae32"),
                            CodigoBanco = "073",
                            NomeInstituicao = "BB Banco Popular do Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("61cd6140-7e5c-4225-8034-0ba120c695b0"),
                            CodigoBanco = "074",
                            NomeInstituicao = "Banco J. Safra S.A"
                        },
                        new
                        {
                            Id = new Guid("fe8babe3-646b-4ad1-9446-0a5e30b5604a"),
                            CodigoBanco = "075",
                            NomeInstituicao = "Banco CR2 S/A"
                        },
                        new
                        {
                            Id = new Guid("7f57f382-581c-455a-8ca2-8edd708b22b5"),
                            CodigoBanco = "076",
                            NomeInstituicao = "Banco KEB do Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("c3c5fdb7-bce1-4e54-9ab3-cf87d1f155cc"),
                            CodigoBanco = "077",
                            NomeInstituicao = "Banco Inter S/A"
                        },
                        new
                        {
                            Id = new Guid("2c3d10c4-8906-4a36-8ed9-6949c33cfa69"),
                            CodigoBanco = "078",
                            NomeInstituicao = "BES Investimentos do Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("2a31b71f-fb9f-45ed-92fc-2b6746edeaf7"),
                            CodigoBanco = "079",
                            NomeInstituicao = "JBS Banco S/A"
                        },
                        new
                        {
                            Id = new Guid("abfa2990-c849-416a-98b5-7912fd1f8b66"),
                            CodigoBanco = "081",
                            NomeInstituicao = "Concórdia Banco S.A."
                        },
                        new
                        {
                            Id = new Guid("1cb3eb5d-8e37-4597-b0f1-70e3a2a26ca1"),
                            CodigoBanco = "082",
                            NomeInstituicao = "Banco Topázio S.A"
                        },
                        new
                        {
                            Id = new Guid("05c42d69-de0e-4f16-bf9c-5a36a5f23d0b"),
                            CodigoBanco = "083",
                            NomeInstituicao = "Banco da China Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("ff8eb2d5-5e07-4fe4-8040-bfe3bc1955a0"),
                            CodigoBanco = "096",
                            NomeInstituicao = "Banco BM&F de Serviços de Liquidação e Custodia S.A."
                        },
                        new
                        {
                            Id = new Guid("1ff1f1cc-bf6c-46ed-8f2f-5b276601b88e"),
                            CodigoBanco = "104",
                            NomeInstituicao = "Caixa Econômica Federal"
                        },
                        new
                        {
                            Id = new Guid("6a2cdb2c-fb02-4eba-b6b7-cacb74c470e9"),
                            CodigoBanco = "107",
                            NomeInstituicao = "Banco BBM S/A"
                        },
                        new
                        {
                            Id = new Guid("9626fa50-1087-4ef5-be92-7ac169744cff"),
                            CodigoBanco = "151",
                            NomeInstituicao = "Banco Nossa Caixa S.A"
                        },
                        new
                        {
                            Id = new Guid("c40f5cd7-90a6-4f0e-941c-e78319a86f72"),
                            CodigoBanco = "184",
                            NomeInstituicao = "Banco Itaú BBA S.A."
                        },
                        new
                        {
                            Id = new Guid("78e24099-e684-448a-ab03-4def5d3b2531"),
                            CodigoBanco = "204",
                            NomeInstituicao = "Banco Bradesco Cartões S.A."
                        },
                        new
                        {
                            Id = new Guid("7e95a8b6-8199-45bb-b76f-59275abf81b2"),
                            CodigoBanco = "208",
                            NomeInstituicao = "Banco UBS Pactual S.A."
                        },
                        new
                        {
                            Id = new Guid("303a7a19-e6a4-4eef-8a37-bd16a4983fa7"),
                            CodigoBanco = "212",
                            NomeInstituicao = "Banco Matone S.A."
                        },
                        new
                        {
                            Id = new Guid("fab0b568-7107-4887-9277-f19bc19a4d56"),
                            CodigoBanco = "213",
                            NomeInstituicao = "Banco Arbi S.A."
                        },
                        new
                        {
                            Id = new Guid("4cd3e561-daeb-44e3-84ff-31b36d5277be"),
                            CodigoBanco = "214",
                            NomeInstituicao = "Banco Dibens S.A"
                        },
                        new
                        {
                            Id = new Guid("80fc3993-f363-417f-b7bc-3f9ab7f0c6d7"),
                            CodigoBanco = "215",
                            NomeInstituicao = "Banco Comercial e de Investimento Sudameris S.A."
                        },
                        new
                        {
                            Id = new Guid("1e9bd700-ea58-4e5d-bf7a-ff79d073a7a6"),
                            CodigoBanco = "217",
                            NomeInstituicao = "Banco John Deere S.A."
                        },
                        new
                        {
                            Id = new Guid("6c5aa950-ab4a-41cd-ab2b-f6335a6438b0"),
                            CodigoBanco = "218",
                            NomeInstituicao = "Banco Bonsucesso S.A."
                        },
                        new
                        {
                            Id = new Guid("2d1441db-fe02-4975-a312-c4c8688b9ad8"),
                            CodigoBanco = "222",
                            NomeInstituicao = "Banco Calyon brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("ad333ea3-0091-4583-ad8f-38e0271850be"),
                            CodigoBanco = "224",
                            NomeInstituicao = "Banco Fibra S.A"
                        },
                        new
                        {
                            Id = new Guid("0777f2dc-8615-4f92-8e4f-a4cf9dfbf62a"),
                            CodigoBanco = "225",
                            NomeInstituicao = "Banco Brascan S.A."
                        },
                        new
                        {
                            Id = new Guid("0146d450-f9d2-4dec-8ff2-180c92a88289"),
                            CodigoBanco = "229",
                            NomeInstituicao = "Banco Cruzeiro Do Sul S.A."
                        },
                        new
                        {
                            Id = new Guid("cf250596-6097-4225-81ea-f2a2331fca2b"),
                            CodigoBanco = "230",
                            NomeInstituicao = "Unicard Banco Múltiplo S.A."
                        },
                        new
                        {
                            Id = new Guid("cfc920b3-89d5-4d06-91b1-8f5729e8d3a0"),
                            CodigoBanco = "233",
                            NomeInstituicao = "Banco GE Capital S.A."
                        },
                        new
                        {
                            Id = new Guid("655048a4-6814-4cb5-94ee-f10e6d2bd3d5"),
                            CodigoBanco = "237",
                            NomeInstituicao = "Banco Bradesco S.A."
                        },
                        new
                        {
                            Id = new Guid("f96432b8-d78e-49ff-af06-2645b44e1a52"),
                            CodigoBanco = "241",
                            NomeInstituicao = "Banco Classico S.A."
                        },
                        new
                        {
                            Id = new Guid("63dd9b57-d551-4161-b3d5-cc95f4946ba3"),
                            CodigoBanco = "243",
                            NomeInstituicao = "Banco Máxima S.A."
                        },
                        new
                        {
                            Id = new Guid("5ad477f4-f394-413c-9b6d-38c867ebe1f2"),
                            CodigoBanco = "246",
                            NomeInstituicao = "Banco ABC Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("4ac281d8-657c-48be-afad-583875a7204e"),
                            CodigoBanco = "248",
                            NomeInstituicao = "Banco Boavista Interatlantico S.A"
                        },
                        new
                        {
                            Id = new Guid("298a96b9-115a-49b7-9280-2931d2217183"),
                            CodigoBanco = "249",
                            NomeInstituicao = "Banco Investicred Unibanco S.A."
                        },
                        new
                        {
                            Id = new Guid("eb8fbc12-2f69-4db4-a745-d8026523c6e4"),
                            CodigoBanco = "250",
                            NomeInstituicao = "Banco Schahin S.A."
                        },
                        new
                        {
                            Id = new Guid("e769614b-4c11-4fea-bae6-6cf66be99f9f"),
                            CodigoBanco = "254",
                            NomeInstituicao = "Paraná Banco S.A."
                        },
                        new
                        {
                            Id = new Guid("84107cca-72c2-4a09-99c1-f5865b51d4ba"),
                            CodigoBanco = "263",
                            NomeInstituicao = "Banco Cacique S.A."
                        },
                        new
                        {
                            Id = new Guid("48cab143-fc11-4401-a29f-8f4e45833dcc"),
                            CodigoBanco = "265",
                            NomeInstituicao = "Banco Fator S.A"
                        },
                        new
                        {
                            Id = new Guid("18630d11-2f12-4e8e-be04-19509e2eaf05"),
                            CodigoBanco = "266",
                            NomeInstituicao = "Banco Cedula S.A"
                        },
                        new
                        {
                            Id = new Guid("d599e8f4-4f9f-4ddb-9715-8112d9626e80"),
                            CodigoBanco = "300",
                            NomeInstituicao = "Banco de La Nacion Argentina"
                        },
                        new
                        {
                            Id = new Guid("32c5a55c-056f-4d81-8bde-29dc97aa8829"),
                            CodigoBanco = "318",
                            NomeInstituicao = "Banco BMG S.A."
                        },
                        new
                        {
                            Id = new Guid("d13de2a0-1882-4a2b-8459-4bde7c84d4f1"),
                            CodigoBanco = "320",
                            NomeInstituicao = "Banco Industrial e Comercial S.A"
                        },
                        new
                        {
                            Id = new Guid("47f9628b-8c47-4af6-8e0c-6f3b034cbf79"),
                            CodigoBanco = "341",
                            NomeInstituicao = "Banco Itaú S.A"
                        },
                        new
                        {
                            Id = new Guid("b52d4702-894a-4cac-9dee-845fa97a595e"),
                            CodigoBanco = "366",
                            NomeInstituicao = "Banco Societé Generale Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("4abc26bf-6e15-462c-bb48-f4fffd5946de"),
                            CodigoBanco = "370",
                            NomeInstituicao = "Banco Westlb do Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("eab1b3d8-5313-46f9-a7d8-25c9712c66de"),
                            CodigoBanco = "376",
                            NomeInstituicao = "Banco J.P. Morgan S.A."
                        },
                        new
                        {
                            Id = new Guid("84b88368-86cf-4476-a197-7b937b0e5741"),
                            CodigoBanco = "389",
                            NomeInstituicao = "Banco Mercantil do Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("69d1b4cb-667a-49b9-90a8-ae1bc91253f0"),
                            CodigoBanco = "394",
                            NomeInstituicao = "Banco Finasa BMC S.A."
                        },
                        new
                        {
                            Id = new Guid("7b4591eb-7d22-4996-a0cd-9dcf06ad32fd"),
                            CodigoBanco = "399",
                            NomeInstituicao = "HSBC Bank Brasil S.A. – Banco Múltiplo"
                        },
                        new
                        {
                            Id = new Guid("7cd97832-4135-4dc9-8d7f-f46efb0e8a6b"),
                            CodigoBanco = "409",
                            NomeInstituicao = "Unibanco-União de Bancos Brasileiros S.A"
                        },
                        new
                        {
                            Id = new Guid("3e9e3801-5b7b-472d-ad6f-dd42b3552fd2"),
                            CodigoBanco = "412",
                            NomeInstituicao = "Banco Capital S.A."
                        },
                        new
                        {
                            Id = new Guid("b02c9bc2-9f7c-4b83-9e81-f3b6ffab44f9"),
                            CodigoBanco = "422",
                            NomeInstituicao = "Banco Safra S.A."
                        },
                        new
                        {
                            Id = new Guid("1f413bed-498e-4b57-87fd-b806be885bf0"),
                            CodigoBanco = "453",
                            NomeInstituicao = "Banco Rural S.A"
                        },
                        new
                        {
                            Id = new Guid("5d82b18e-1260-4d1f-bdbe-526f9203253e"),
                            CodigoBanco = "456",
                            NomeInstituicao = "Banco de Tokyo-Mitsubishi UFJ Brasil S/A"
                        },
                        new
                        {
                            Id = new Guid("d49443c0-c1bc-49d2-a11f-df266ac32724"),
                            CodigoBanco = "464",
                            NomeInstituicao = "Banco Sumitomo Mitsui Brasileiro S.A"
                        },
                        new
                        {
                            Id = new Guid("b7ff2afc-9d81-4e14-b638-84625021e512"),
                            CodigoBanco = "473",
                            NomeInstituicao = "Banco Caixa Geral – Brasil S.A."
                        },
                        new
                        {
                            Id = new Guid("ea1732d8-0057-4f4a-b9b0-7be83bd15002"),
                            CodigoBanco = "477",
                            NomeInstituicao = "Citibank N.A."
                        },
                        new
                        {
                            Id = new Guid("75e9866b-20fa-42d6-ac6a-ff8ee33e6b3d"),
                            CodigoBanco = "479",
                            NomeInstituicao = "Banco Itaubank S.A"
                        },
                        new
                        {
                            Id = new Guid("adf267d7-c2e9-4997-b7b2-e37dc79e1423"),
                            CodigoBanco = "487",
                            NomeInstituicao = "Deutsche Bank S.A. – Banco Alemao"
                        },
                        new
                        {
                            Id = new Guid("51fcd730-4a53-4bb0-9d53-40435ef0a682"),
                            CodigoBanco = "488",
                            NomeInstituicao = "JPMorgan Chase Bank, National Association"
                        },
                        new
                        {
                            Id = new Guid("b72d2ab8-ea1f-4f85-ad68-a2cf59622d0f"),
                            CodigoBanco = "492",
                            NomeInstituicao = "Ing Bank N.V."
                        },
                        new
                        {
                            Id = new Guid("6652f63e-0970-43aa-b86c-c7d335890d00"),
                            CodigoBanco = "494",
                            NomeInstituicao = "Banco de la Republica Oriental del Uruguay"
                        },
                        new
                        {
                            Id = new Guid("5c578194-73d1-47bb-b73e-b75f94c01b7c"),
                            CodigoBanco = "495",
                            NomeInstituicao = "Banco de la Provincia de Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("1baba687-24c0-4c5e-8046-d869bd319206"),
                            CodigoBanco = "505",
                            NomeInstituicao = "Banco Credit Suisse (Brasil) S.A."
                        },
                        new
                        {
                            Id = new Guid("bfb47f14-21ee-47c0-a910-10dc5f5745f3"),
                            CodigoBanco = "600",
                            NomeInstituicao = "Banco Luso Brasileiro S.A"
                        },
                        new
                        {
                            Id = new Guid("4cc4bf96-1a03-4d1f-ad38-cbc308c64f69"),
                            CodigoBanco = "604",
                            NomeInstituicao = "Banco Industrial Do Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("011d77b7-95b3-4007-a9f3-84a28ff379bb"),
                            CodigoBanco = "610",
                            NomeInstituicao = "Banco VR S.A"
                        },
                        new
                        {
                            Id = new Guid("a8e54647-c264-4bcd-b577-46d700b240be"),
                            CodigoBanco = "611",
                            NomeInstituicao = "Banco Paulista S.A."
                        },
                        new
                        {
                            Id = new Guid("0132ba76-e5d9-4bb7-87b6-d3ec7f7f15e9"),
                            CodigoBanco = "612",
                            NomeInstituicao = "Banco Guanabara S.A."
                        },
                        new
                        {
                            Id = new Guid("fd5a5b8f-a8f8-4081-8977-cf536c96820c"),
                            CodigoBanco = "613",
                            NomeInstituicao = "Banco Pecunia S.A"
                        },
                        new
                        {
                            Id = new Guid("c54e31fc-a5ce-4d3e-9e00-cfdd37f965a8"),
                            CodigoBanco = "623",
                            NomeInstituicao = "Banco Panamericano S.A."
                        },
                        new
                        {
                            Id = new Guid("3c0145e4-33da-43ab-9dfc-9e6f08597983"),
                            CodigoBanco = "626",
                            NomeInstituicao = "Banco Ficsa S.A"
                        },
                        new
                        {
                            Id = new Guid("ec6d0360-4b79-4e47-b92c-312022fb2bb4"),
                            CodigoBanco = "630",
                            NomeInstituicao = "Banco Intercap S.A"
                        },
                        new
                        {
                            Id = new Guid("2da09d07-8404-4676-886f-65917d9954aa"),
                            CodigoBanco = "633",
                            NomeInstituicao = "Banco Rendimento S.A."
                        },
                        new
                        {
                            Id = new Guid("88a18136-b25e-4d67-96c6-03c9e9d607c5"),
                            CodigoBanco = "634",
                            NomeInstituicao = "Banco Triangulo S.A."
                        },
                        new
                        {
                            Id = new Guid("e3da7144-a5af-402c-9ad9-f52666fe5385"),
                            CodigoBanco = "637",
                            NomeInstituicao = "Banco Sofisa S.A"
                        },
                        new
                        {
                            Id = new Guid("eacfcda3-bc62-477a-a7ab-34b71cd22759"),
                            CodigoBanco = "638",
                            NomeInstituicao = "Banco Prosper S.A."
                        },
                        new
                        {
                            Id = new Guid("50872498-73a6-49e6-ad04-ab81cb12bc7a"),
                            CodigoBanco = "641",
                            NomeInstituicao = "Banco Alvorada S.A."
                        },
                        new
                        {
                            Id = new Guid("3ab75b43-1ddc-4865-96c2-24edac562b5a"),
                            CodigoBanco = "643",
                            NomeInstituicao = "Banco Pine S.A."
                        },
                        new
                        {
                            Id = new Guid("ca7ff0a9-c5d3-47cc-8b33-a39fa527f170"),
                            CodigoBanco = "652",
                            NomeInstituicao = "Itaú Unibanco Banco Múltiplo S.A"
                        },
                        new
                        {
                            Id = new Guid("abe454d9-c698-4732-a81c-33bd9dbe0b0b"),
                            CodigoBanco = "653",
                            NomeInstituicao = "Banco Indusval S.A."
                        },
                        new
                        {
                            Id = new Guid("77939e8e-5064-48c7-8ed2-e28b63840e9c"),
                            CodigoBanco = "654",
                            NomeInstituicao = "Banco A.J. Renner S.A"
                        },
                        new
                        {
                            Id = new Guid("f0fd67e3-4a58-4b5f-afdc-dc2bdf31a343"),
                            CodigoBanco = "655",
                            NomeInstituicao = "Banco Votorantim S.A"
                        },
                        new
                        {
                            Id = new Guid("99eab4dc-a7f5-4cc1-a5f9-db26a2a0768f"),
                            CodigoBanco = "707",
                            NomeInstituicao = "Banco Daycoval S.A."
                        },
                        new
                        {
                            Id = new Guid("5966641f-64ab-4330-9cfc-982ab6b0602e"),
                            CodigoBanco = "719",
                            NomeInstituicao = "Banif – Banco Internacional do Funchal (Brasil), S.A"
                        },
                        new
                        {
                            Id = new Guid("bc88fcd8-6a4e-4f0d-83af-d20a3b21437b"),
                            CodigoBanco = "721",
                            NomeInstituicao = "Banco Credibel S.A."
                        },
                        new
                        {
                            Id = new Guid("b470bf86-8133-48bf-9056-00578aeac1a9"),
                            CodigoBanco = "734",
                            NomeInstituicao = "Banco Gerdau S.A"
                        },
                        new
                        {
                            Id = new Guid("c69ba273-020b-455b-859e-79f4e1458699"),
                            CodigoBanco = "735",
                            NomeInstituicao = "Banco Pottencial S.A"
                        },
                        new
                        {
                            Id = new Guid("2476834d-1b9a-48ac-b0cf-96e1e4b095a2"),
                            CodigoBanco = "738",
                            NomeInstituicao = "Banco Morada S.A"
                        },
                        new
                        {
                            Id = new Guid("48e87388-8172-41ed-8cf0-5afaa02c2d7a"),
                            CodigoBanco = "739",
                            NomeInstituicao = "Banco BGN S.A."
                        },
                        new
                        {
                            Id = new Guid("c1dc2533-4900-400f-9752-fef2d5b9b693"),
                            CodigoBanco = "740",
                            NomeInstituicao = "Banco Barclays S.A"
                        },
                        new
                        {
                            Id = new Guid("f3833c8f-f80f-4360-8488-cce41198c22a"),
                            CodigoBanco = "741",
                            NomeInstituicao = "Banco Ribeirao Preto S.A"
                        },
                        new
                        {
                            Id = new Guid("df8414cb-ff84-476b-b9bb-24a3d070da2f"),
                            CodigoBanco = "743",
                            NomeInstituicao = "Banco Semear S.A."
                        },
                        new
                        {
                            Id = new Guid("da9a2c22-ad29-4b36-bab7-67ef0a9647f1"),
                            CodigoBanco = "745",
                            NomeInstituicao = "Banco Citibank S.A."
                        },
                        new
                        {
                            Id = new Guid("7d638c3a-0ef5-4024-92f3-d10a9cdb7d7b"),
                            CodigoBanco = "746",
                            NomeInstituicao = "Banco Modal S.A"
                        },
                        new
                        {
                            Id = new Guid("14465e81-5fd2-4ee3-bd3a-1456578982f4"),
                            CodigoBanco = "747",
                            NomeInstituicao = "Banco Rabobank International Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("e5c8018d-f600-4e4a-aed2-3ae50787e6ca"),
                            CodigoBanco = "748",
                            NomeInstituicao = "Banco Cooperativo Sicredi S.A."
                        },
                        new
                        {
                            Id = new Guid("9638ecd6-a03d-42d1-bcfd-7a7ea26fa619"),
                            CodigoBanco = "749",
                            NomeInstituicao = "Banco Simples S.A"
                        },
                        new
                        {
                            Id = new Guid("8d1bc268-594f-4ddf-873c-0c6d8f49b3ea"),
                            CodigoBanco = "751",
                            NomeInstituicao = "Dresdner Bank Brasil S.A. Banco Multiplo"
                        },
                        new
                        {
                            Id = new Guid("bfdfeb8b-ffb6-4b3c-8bee-dc08fbb819eb"),
                            CodigoBanco = "752",
                            NomeInstituicao = "Banco BNP Paribas Brasil S.A"
                        },
                        new
                        {
                            Id = new Guid("3ad668eb-bd09-4f30-a839-7405e59c4bd6"),
                            CodigoBanco = "753",
                            NomeInstituicao = "NBC Bank Brasil S. A. – Banco Múltiplo"
                        },
                        new
                        {
                            Id = new Guid("93fb55ec-1377-4267-a214-68d4a653a1ba"),
                            CodigoBanco = "756",
                            NomeInstituicao = "Banco Cooperativo do Brasil S.A. – Bancoob"
                        },
                        new
                        {
                            Id = new Guid("2877aa43-6787-4fd3-916b-b45ef6d9d957"),
                            CodigoBanco = "757",
                            NomeInstituicao = "Banco KEB do Brasil S.A."
                        });
                });

            modelBuilder.Entity("DevIO.Business.Models.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("BancoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime");

                    b.Property<string>("NomeRazaoSocialTitular")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDaAgencia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDaConta")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("DevIO.Business.Models.ContaBancaria", b =>
                {
                    b.HasOne("DevIO.Business.Models.Banco", "Banco")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("BancoId")
                        .IsRequired();

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("DevIO.Business.Models.Banco", b =>
                {
                    b.Navigation("ContasBancarias");
                });
#pragma warning restore 612, 618
        }
    }
}
