using System;
using System.Collections.Generic;
using System.Text;

namespace DevIO.Business.Models
{
    public class Banco : Entity
    {
        public string CodigoBanco { get; private set; }
        public string NomeInstituicao { get; private set; }

        /* EF Relation */
        public IEnumerable<ContaBancaria> ContasBancarias { get; set; }

        public static List<Banco> Gerador()
        {
            return new List<Banco>
            {
                new Banco{CodigoBanco = "001", NomeInstituicao = "Banco do Brasil S.A."},
                new Banco{CodigoBanco = "003", NomeInstituicao = "Banco da Amazonia S.A."},
                new Banco{CodigoBanco = "004", NomeInstituicao = "Banco do Nordeste do Brasil S.A."},
                new Banco{CodigoBanco = "012", NomeInstituicao = "Banco Standard de Investimentos S.A."},
                new Banco{CodigoBanco = "014", NomeInstituicao = "Natixis Brasil S.A. Banco Múltiplo"},
                new Banco{CodigoBanco = "019", NomeInstituicao = "Banco Azteca do Brasil S.A"},
                new Banco{CodigoBanco = "021", NomeInstituicao = "Banestes S.A. Banco do Estado do Espírito Santo S.A."},
                new Banco{CodigoBanco = "024", NomeInstituicao = "Banco de Pernambuco S.A. – BANDEPE"},
                new Banco{CodigoBanco = "025", NomeInstituicao = "Banco Alfa S.A"},
                new Banco{CodigoBanco = "029", NomeInstituicao = "Banco Banerj S.A"},
                new Banco{CodigoBanco = "031", NomeInstituicao = "Banco Beg S.A."},
                new Banco{CodigoBanco = "033", NomeInstituicao = "Banco Santander (Brasil) S.A"},
                new Banco{CodigoBanco = "036", NomeInstituicao = "Banco Bradesco BBI S.A."},
                new Banco{CodigoBanco = "037", NomeInstituicao = "Banco do Estado do Pará S.A"},
                new Banco{CodigoBanco = "040", NomeInstituicao = "Banco Cargil S.A"},
                new Banco{CodigoBanco = "041", NomeInstituicao = "Banco do Estado do Rio Grade do Sul S.A."},
                new Banco{CodigoBanco = "044", NomeInstituicao = "Banco BVA S.A"},
                new Banco{CodigoBanco = "045", NomeInstituicao = "Banco Opportunity S.A."},
                new Banco{CodigoBanco = "047", NomeInstituicao = "Banco do Estado de Sergipe S.A"},
                new Banco{CodigoBanco = "062", NomeInstituicao = "Hipercard Banco Múltiplo S.A"},
                new Banco{CodigoBanco = "063", NomeInstituicao = "Banco IBI S.A. – Banco Múltiplo"},
                new Banco{CodigoBanco = "065", NomeInstituicao = "Banco Lemon S.A"},
                new Banco{CodigoBanco = "066", NomeInstituicao = "Banco Morgan Stanley S.A"},
                new Banco{CodigoBanco = "069", NomeInstituicao = "BPN Brasil Banco Múltiplo S.A."},
                new Banco{CodigoBanco = "070", NomeInstituicao = "BRB – Banco de Brasilia S.A"},
                new Banco{CodigoBanco = "072", NomeInstituicao = "Banco Rural Mais S.A"},
                new Banco{CodigoBanco = "073", NomeInstituicao = "BB Banco Popular do Brasil S.A."},
                new Banco{CodigoBanco = "074", NomeInstituicao = "Banco J. Safra S.A"},
                new Banco{CodigoBanco = "075", NomeInstituicao = "Banco CR2 S/A"},
                new Banco{CodigoBanco = "076", NomeInstituicao = "Banco KEB do Brasil S.A"},
                new Banco{CodigoBanco = "077", NomeInstituicao = "Banco Inter S/A"},
                new Banco{CodigoBanco = "078", NomeInstituicao = "BES Investimentos do Brasil S.A."},
                new Banco{CodigoBanco = "079", NomeInstituicao = "JBS Banco S/A"},
                new Banco{CodigoBanco = "081", NomeInstituicao = "Concórdia Banco S.A."},
                new Banco{CodigoBanco = "082", NomeInstituicao = "Banco Topázio S.A"},
                new Banco{CodigoBanco = "083", NomeInstituicao = "Banco da China Brasil S.A"},
                new Banco{CodigoBanco = "096", NomeInstituicao = "Banco BM&F de Serviços de Liquidação e Custodia S.A."},
                new Banco{CodigoBanco = "104", NomeInstituicao = "Caixa Econômica Federal"},
                new Banco{CodigoBanco = "107", NomeInstituicao = "Banco BBM S/A"},
                new Banco{CodigoBanco = "151", NomeInstituicao = "Banco Nossa Caixa S.A"},
                new Banco{CodigoBanco = "184", NomeInstituicao = "Banco Itaú BBA S.A."},
                new Banco{CodigoBanco = "204", NomeInstituicao = "Banco Bradesco Cartões S.A."},
                new Banco{CodigoBanco = "208", NomeInstituicao = "Banco UBS Pactual S.A."},
                new Banco{CodigoBanco = "212", NomeInstituicao = "Banco Matone S.A."},
                new Banco{CodigoBanco = "213", NomeInstituicao = "Banco Arbi S.A."},
                new Banco{CodigoBanco = "214", NomeInstituicao = "Banco Dibens S.A"},
                new Banco{CodigoBanco = "215", NomeInstituicao = "Banco Comercial e de Investimento Sudameris S.A."},
                new Banco{CodigoBanco = "217", NomeInstituicao = "Banco John Deere S.A."},
                new Banco{CodigoBanco = "218", NomeInstituicao = "Banco Bonsucesso S.A."},
                new Banco{CodigoBanco = "222", NomeInstituicao = "Banco Calyon brasil S.A."},
                new Banco{CodigoBanco = "224", NomeInstituicao = "Banco Fibra S.A"},
                new Banco{CodigoBanco = "225", NomeInstituicao = "Banco Brascan S.A."},
                new Banco{CodigoBanco = "229", NomeInstituicao = "Banco Cruzeiro Do Sul S.A."},
                new Banco{CodigoBanco = "230", NomeInstituicao = "Unicard Banco Múltiplo S.A."},
                new Banco{CodigoBanco = "233", NomeInstituicao = "Banco GE Capital S.A."},
                new Banco{CodigoBanco = "237", NomeInstituicao = "Banco Bradesco S.A."},
                new Banco{CodigoBanco = "241", NomeInstituicao = "Banco Classico S.A."},
                new Banco{CodigoBanco = "243", NomeInstituicao = "Banco Máxima S.A."},
                new Banco{CodigoBanco = "246", NomeInstituicao = "Banco ABC Brasil S.A."},
                new Banco{CodigoBanco = "248", NomeInstituicao = "Banco Boavista Interatlantico S.A"},
                new Banco{CodigoBanco = "249", NomeInstituicao = "Banco Investicred Unibanco S.A."},
                new Banco{CodigoBanco = "250", NomeInstituicao = "Banco Schahin S.A."},
                new Banco{CodigoBanco = "254", NomeInstituicao = "Paraná Banco S.A."},
                new Banco{CodigoBanco = "263", NomeInstituicao = "Banco Cacique S.A."},
                new Banco{CodigoBanco = "265", NomeInstituicao = "Banco Fator S.A"},
                new Banco{CodigoBanco = "266", NomeInstituicao = "Banco Cedula S.A"},
                new Banco{CodigoBanco = "300", NomeInstituicao = "Banco de La Nacion Argentina"},
                new Banco{CodigoBanco = "318", NomeInstituicao = "Banco BMG S.A."},
                new Banco{CodigoBanco = "320", NomeInstituicao = "Banco Industrial e Comercial S.A"},
                new Banco{CodigoBanco = "341", NomeInstituicao = "Banco Itaú S.A"},
                new Banco{CodigoBanco = "366", NomeInstituicao = "Banco Societé Generale Brasil S.A."},
                new Banco{CodigoBanco = "370", NomeInstituicao = "Banco Westlb do Brasil S.A"},
                new Banco{CodigoBanco = "376", NomeInstituicao = "Banco J.P. Morgan S.A."},
                new Banco{CodigoBanco = "389", NomeInstituicao = "Banco Mercantil do Brasil S.A."},
                new Banco{CodigoBanco = "394", NomeInstituicao = "Banco Finasa BMC S.A."},
                new Banco{CodigoBanco = "399", NomeInstituicao = "HSBC Bank Brasil S.A. – Banco Múltiplo"},
                new Banco{CodigoBanco = "409", NomeInstituicao = "Unibanco-União de Bancos Brasileiros S.A"},
                new Banco{CodigoBanco = "412", NomeInstituicao = "Banco Capital S.A."},
                new Banco{CodigoBanco = "422", NomeInstituicao = "Banco Safra S.A."},
                new Banco{CodigoBanco = "453", NomeInstituicao = "Banco Rural S.A"},
                new Banco{CodigoBanco = "456", NomeInstituicao = "Banco de Tokyo-Mitsubishi UFJ Brasil S/A"},
                new Banco{CodigoBanco = "464", NomeInstituicao = "Banco Sumitomo Mitsui Brasileiro S.A"},
                new Banco{CodigoBanco = "473", NomeInstituicao = "Banco Caixa Geral – Brasil S.A."},
                new Banco{CodigoBanco = "477", NomeInstituicao = "Citibank N.A."},
                new Banco{CodigoBanco = "479", NomeInstituicao = "Banco Itaubank S.A"},
                new Banco{CodigoBanco = "487", NomeInstituicao = "Deutsche Bank S.A. – Banco Alemao"},
                new Banco{CodigoBanco = "488", NomeInstituicao = "JPMorgan Chase Bank, National Association"},
                new Banco{CodigoBanco = "492", NomeInstituicao = "Ing Bank N.V."},
                new Banco{CodigoBanco = "494", NomeInstituicao = "Banco de la Republica Oriental del Uruguay"},
                new Banco{CodigoBanco = "495", NomeInstituicao = "Banco de la Provincia de Buenos Aires"},
                new Banco{CodigoBanco = "505", NomeInstituicao = "Banco Credit Suisse (Brasil) S.A."},
                new Banco{CodigoBanco = "600", NomeInstituicao = "Banco Luso Brasileiro S.A"},
                new Banco{CodigoBanco = "604", NomeInstituicao = "Banco Industrial Do Brasil S.A"},
                new Banco{CodigoBanco = "610", NomeInstituicao = "Banco VR S.A"},
                new Banco{CodigoBanco = "611", NomeInstituicao = "Banco Paulista S.A."},
                new Banco{CodigoBanco = "612", NomeInstituicao = "Banco Guanabara S.A."},
                new Banco{CodigoBanco = "613", NomeInstituicao = "Banco Pecunia S.A"},
                new Banco{CodigoBanco = "623", NomeInstituicao = "Banco Panamericano S.A."},
                new Banco{CodigoBanco = "626", NomeInstituicao = "Banco Ficsa S.A"},
                new Banco{CodigoBanco = "630", NomeInstituicao = "Banco Intercap S.A"},
                new Banco{CodigoBanco = "633", NomeInstituicao = "Banco Rendimento S.A."},
                new Banco{CodigoBanco = "634", NomeInstituicao = "Banco Triangulo S.A."},
                new Banco{CodigoBanco = "637", NomeInstituicao = "Banco Sofisa S.A"},
                new Banco{CodigoBanco = "638", NomeInstituicao = "Banco Prosper S.A."},
                new Banco{CodigoBanco = "641", NomeInstituicao = "Banco Alvorada S.A."},
                new Banco{CodigoBanco = "643", NomeInstituicao = "Banco Pine S.A."},
                new Banco{CodigoBanco = "652", NomeInstituicao = "Itaú Unibanco Banco Múltiplo S.A"},
                new Banco{CodigoBanco = "653", NomeInstituicao = "Banco Indusval S.A."},
                new Banco{CodigoBanco = "654", NomeInstituicao = "Banco A.J. Renner S.A"},
                new Banco{CodigoBanco = "655", NomeInstituicao = "Banco Votorantim S.A"},
                new Banco{CodigoBanco = "707", NomeInstituicao = "Banco Daycoval S.A."},
                new Banco{CodigoBanco = "719", NomeInstituicao = "Banif – Banco Internacional do Funchal (Brasil), S.A"},
                new Banco{CodigoBanco = "721", NomeInstituicao = "Banco Credibel S.A."},
                new Banco{CodigoBanco = "734", NomeInstituicao = "Banco Gerdau S.A"},
                new Banco{CodigoBanco = "735", NomeInstituicao = "Banco Pottencial S.A"},
                new Banco{CodigoBanco = "738", NomeInstituicao = "Banco Morada S.A"},
                new Banco{CodigoBanco = "739", NomeInstituicao = "Banco BGN S.A."},
                new Banco{CodigoBanco = "740", NomeInstituicao = "Banco Barclays S.A"},
                new Banco{CodigoBanco = "741", NomeInstituicao = "Banco Ribeirao Preto S.A"},
                new Banco{CodigoBanco = "743", NomeInstituicao = "Banco Semear S.A."},
                new Banco{CodigoBanco = "745", NomeInstituicao = "Banco Citibank S.A."},
                new Banco{CodigoBanco = "746", NomeInstituicao = "Banco Modal S.A"},
                new Banco{CodigoBanco = "747", NomeInstituicao = "Banco Rabobank International Brasil S.A"},
                new Banco{CodigoBanco = "748", NomeInstituicao = "Banco Cooperativo Sicredi S.A."},
                new Banco{CodigoBanco = "749", NomeInstituicao = "Banco Simples S.A"},
                new Banco{CodigoBanco = "751", NomeInstituicao = "Dresdner Bank Brasil S.A. Banco Multiplo"},
                new Banco{CodigoBanco = "752", NomeInstituicao = "Banco BNP Paribas Brasil S.A"},
                new Banco{CodigoBanco = "753", NomeInstituicao = "NBC Bank Brasil S. A. – Banco Múltiplo"},
                new Banco{CodigoBanco = "756", NomeInstituicao = "Banco Cooperativo do Brasil S.A. – Bancoob"},
                new Banco{CodigoBanco = "757", NomeInstituicao = "Banco KEB do Brasil S.A."}
            };
        }
    }
}
